import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lista de Tareas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <div className="min-h-screen text-white" style={{ background: "linear-gradient(135deg, #2d3748, #4a5568)" }}>
          <Navbar />
          <div className="container mx-auto py-8 p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
